spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/painer?serverTimezon=Asia/Seoul
    username: painer
    password: lh015931

  mail:
    host: smtp.gmail.com
    port: 587
    username: lhidns@gmail.com
    password: yspannfspejcrfqf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 80

